### ISSUE TITLE
Ships: missing ship ability description

### ISSUE THREAD

**Issue by Iliasgx** [STFCcommunity/data#45]
Description of the ship ability is missing for the following ships:

- [x] Botany Bay
- [x] D'Vor
- [x] Legionary
- [x] USS Mayflower
- [x] ISS Jellyfish
- [x] USS Franklin
- [x] Hijacked Legionary
- [x] Hijacked Mayflower
- [x] Vi'Dar

**Comment by WebSpider** [comment]
Merged #46 with these descriptions
