### ISSUE TITLE
NorthStar ship ability bonus is incorrect

### ISSUE THREAD

**Issue by WebSpider** [STFCcommunity/data#48]
Ship ability bonus is set to '0' for all levels. This is incorrect.

**Comment by ccMatrix** [comment]
I assumed the percentage values were full numbers between but the North Star actually has a bonus of 0.x %. Will be interesting of the impact when I parse the ship abilities as floats instead of integers...

**Comment by WebSpider** [comment]
Yeah, it's because the ability acts upon a possibly pretty big number, the health of the officers onboard.

**Comment by WebSpider** [comment]
This was fixed in #49
