### ISSUE TITLE
Missing hostile descriptions

### ISSUE THREAD

**Issue by Iliasgx** [STFCcommunity/data#64]
No description found for the following hostiles:
- Assimilated Ferengi Miner
- Assimilated Ferengi Trader ⇔ (3 files)

**Comment by WebSpider** [comment]
I don't have anything that has local translations (English, Russian or whatever language) in it either :/

**Comment by Iliasgx** [comment]
After discussing the descriptions of these hostiles with Ripper, it seems they simply don't have one.
