### ISSUE TITLE
.scrap ---- giving unrelated options

### ISSUE THREAD

**Issue by hamilton1977** [STFCcommunity/data#80]
MrHamster — Today at 8:14 PM
.scrap
KMARS beta
BOT
 — Today at 8:15 PM
Choose the type of information you like
Please choose which information you would like to view for the uss franklin-a from the list below:
Choices
:one:: Tier information

:two:: Total Cost of Ownership (TCO)

:three:: Scrap Information

:four:: Blueprints

:five:: Summaries

:six:: Ship skins

**Comment by hamilton1977** [comment]
it should use the command name to answer this chose.

the .scrap should always resolve to the "scrap information" option even if it has to ask me the fraction and type of ship.

**Comment by WebSpider** [comment]
I fully agree here. I will copy this one to https://github.com/STFCcommunity/botfeedback/ so it doesnt get lost
