### ISSUE TITLE
Expand the officers schema to hold traits

### ISSUE THREAD

**Issue by WebSpider** [STFCcommunity/data#84]
Patch 34 brings traits to officers. 
Each officer can have a number of traits that can be trained to increase away mission critical success factor.

Not every officer has traits, and not every officer has the same amount of traits.

**Comment by ccMatrix** [comment]
Based on the https://www.startrekfleetcommand.com/away-teams/ page I can see

- The amount of traits per officers depends on the officers rarity:
  - Common officers: 0 Traits
  - Uncommon officers: 1 Trait
  - Rare officers: 2 Traits
  - Epic officers: 3 Traits
- Traits can have multiple levels
  - First trait has 3 levels
  - Second trait has 4 levels
  - Third trait has 9 levels
- The percentage a trait adds to critital success depends on the level of it. But I don't see a formula yet and don't have unlocked enough to make a guess. But this seems to be per trait and level and not specific to an officer. E.g. Nero or Picard both have the same boost for their Trait 3 level 9 in their respective trait

So from a schema it looks like Traits could be an array. Then we can even make it required and it would simply be empty for common officers. The elements in the array would contain:

```json
{
  "name": "Captain",
  "level": 3,
  "max_level": 3
}
```

- So name is a string (or a valid value of all the known trait names)
- level is an integer between 0 and 9
- max_level is how many levels this trait has (integer 3, 4 or 9)

Max Level could also be used for the ordering to determine the first, second and third trait or we could add a field `trait` with integer 1, 2, 3.

The main "busy work" is going through all officers and writing down their Trait names and updating that all manually.

**Comment by Iliasgx** [comment]
As ccMatrix suggested, an array would be a good way to go. We should use an extra field `tier` for sorting purposes to make the schema more future proof. If Scopley decices to add a tier 4 with only 3 levels, ordering on `max_level` would not work anymore.

The cost of trait xp seems to be the same across officers of different tiers and rarities, therefor it can be added directly to the traits subschema.

Extension on ccMatrix's schema proposal:
```json
"traits": [{
    "tier": 1,
    "name": "Captain",
    "levels": [{
        "level": 1,
        "trait_xp": 1500,
        "crit_chance": 0.14
    }]
}]

If we don't have the trait names and details from Scopely, we have a big community with helping hands to go through all officers and help accumulate the information.

**Comment by ccMatrix** [comment]
Ah right. I totally forgot about the cost to unlock. I like the tier and level method since it matches up nicely with other objects we have. The names should be easy enough since they are always visible. That's just going through all officers. Time consuming but doable. Getting the cost per level and the crit chance feels way more difficult. I don't expect differences on the officers but we need to test if e.g. tier 1 level 1 of an epic officer costs the same as tier 1 level 1 of uncommon or if there is a pattern that can be copied.

**Comment by Iliasgx** [comment]
Yes, I would suggest getting all the data first before we make changes to the schema. That way we can test our hypothesis of same costs across officers.

**Comment by WebSpider** [comment]
> 
> The main "busy work" is going through all officers and writing down their Trait names and updating that all manually.

I am hoping to get that data in a parseable format soon.

**Comment by ccMatrix** [comment]
My first Trait (Tier 1 Level 1) was 1500
The next was Tier 1 Level 2 for 2700
Tier 1 Level 3 is 3800.

All officers I checked have 1500 trait XP as cost for T1L1

Tier 2 stays locked. Probably until T1L3 is completed.
I don't have more trait XP yet to go further.

**Comment by ccMatrix** [comment]
My guess currently is that trait XP goes up on every level and tier. Will need to prove that once I have T2 unlocked on the officer

**Comment by ccMatrix** [comment]
Oh and I'm currently testing with Khan. So if someone can confirm the same prices on an uncommon or rare officer that would be great

**Comment by Iliasgx** [comment]
> Oh and I'm currently testing with Khan. So if someone can confirm the same prices on an uncommon or rare officer that would be great

I can confirm the same costs for tier 1 level 1 to 3 for Epic Marcus, Epic 5of10 and Rare 1of10. I've no more xp to spend.

**Comment by WebSpider** [comment]
Unfortunately, it looks like I won't be able to get this in parseable format as soon as I'd had hoped. 
Let's see if we can engage the community to get this data for all the officers

**Comment by ccMatrix** [comment]
Trait 2 Level 1 is 7650 trait xp

**Comment by ccMatrix** [comment]
If we get the trait XP info for all the levels we should be able to populate the traits

**Comment by WebSpider** [comment]
PR #83 contains new data in accordance with the suggested schema. 
Unfortunately, I'm still looking for the added critical chance change. Lets add that later on.

**Comment by WebSpider** [comment]
In #83 I have used the following schema, almost identical to the suggestion by @Iliasgx 

```
"traits": [{
    "tier": 1,
    "name": "Captain",
    "levels": [{
        "level": 1,
        "trait_xp": 1500
    }]
}]
```
It looks like the increased crit chances are dependant on mission/trait level combination. I'm hunting the away mission data.
